/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable react/no-unescaped-entities */


import Head from "next/head";

import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
  AiFillFacebook} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";


import kavindu from "../public/profile2-kavindu.jpg";


import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import web7 from "../public/web7.png";
import web8 from "../public/web8.png";
// import web9 from "../public/web9.png";
import web10 from "../public/web10.png";
import web11 from "../public/web11.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [selectedImage, setSelectedImage] = useState(null);

  const handleImageClick = (image) => {
    setSelectedImage(image);
    setShowModal(true);
  };

  const handleCloseModal = () => {
    setShowModal(false);
    setSelectedImage(null);
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kavindu Gunathilaka Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl"> #Kavindugunathilaka</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" 
                  href="https://drive.google.com/drive/folders/16LtMFsMnQpbYszch53ME9Zmms6jdzqm2?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
            
            Kavindu Gunathilaka

            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
            Full Stack Software Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Welcome to my digital nook. I'm a self-taught Full Stack Software Develope  and here, I share my thoughts and what I've learned along the way.
          
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://twitter.com">
                <AiFillTwitterCircle />
              </a>
              <a href="https://www.linkedin.com/in/kavindu-gunathilaka/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/kavindugunathilaka">
                <AiFillGithub />
              </a>
              <a href="https://web.facebook.com/kavindu.gunathilaka.54/">
                <AiFillFacebook />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={kavindu} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
             <br></br>
             Hi, I am Kavindu Gunathilaka . I am a Full Stack Software Developer with expertise in cloud-based solutions,
              Node.js, Java, Spring Boot, and Flutter tech stack. With over two years of experience, 
              I specialize in creating user-friendly and responsive designs that enhance the overall user experience. 
              I have a strong understanding of Front-end Development and I am proficient in using HTML5, CSS, JavaScript, and React JS. 
              My skills also extend to cloud technologies, server-side development with Node.js and Java, and building applications with Spring Boot and Flutter.
              Let's collaborate and bring your ideas to life with innovative and scalable solutions.

              <br></br>

              <span className="text-teal-500">* Special Note </span>
              <br></br>
              
            </p>
            
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Recently, I successfully transitioned from working in a CMS-focused company to exploring new horizons in web development.
             With a strong background in CMS technologies, I have proactively learned and adopted a new tech stack,
              equipping myself with skills in Node , Reac Js , Java. 
              I am now seeking exciting opportunities in a forward-thinking company where 
              I can apply my newfound expertise and contribute to innovative web projects. My adaptability,
               passion for learning, and desire to embrace new challenges position me as a motivated candidate 
               ready to make a positive impact in a new environment.
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                 UI Designs
              </h3>
              <p className="py-2">
              Front-End Developer with expertise in popular frameworks such as
              <br></br>
              <span className="text-teal-500">React</span>
              <br></br>
              <span className="text-teal-500">Angular</span>
              <br />
              <span className="text-teal-500">  Next Js </span>
              <br />

              
                  Experienced in building responsive and interactive web applications using these frameworks. 
                  Proficient in               <br />
                  <span className="text-teal-500"> HTML, CSS, and JavaScript </span>
                     <br />

                  to create seamless user experiences. Strong understanding of component-based architecture and state management.
                   Committed to delivering high-quality code and staying updated with the latest front-end development trends and best practices
              </p>
              
            </div>



            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                For Back End
              </h3>
              <p className="py-2">
              Backend Developer with expertise in <br /> <span className="text-teal-500">Java</span>  <br />
              <span className="text-teal-500">Node Js</span><br />
               for building robust and scalable server-side applications and.
                Proficient in designing RESTful APIs, working with databases, and implementing authentication and authorization mechanisms.
                 Experienced in mobile development using <br /> <span className="text-teal-500">Flutter</span>, <br />creating cross-platform apps with a native-like experience.
                  Strong understanding of asynchronous programming and server deployment. Passionate about creating efficient
                   and reliable backend systems to support modern web and mobile applications
              </p>
             
            </div>



            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Technical Articles</h3>
              <p className="py-2">
              I am also an avid tech enthusiast and maintain a personal tech blog where
               I share my insights and knowledge on various topics related to the tech industry. 
               Through my blog, I strive to provide valuable information, tips, and tutorials to help readers stay updated with the latest trends,
                best practices, and innovations in the tech world. Covering topics such as Software Reviews,Digital Marketing ..., 
                 aim to create engaging and informative content that educates and inspires readers. Visit my blog "devmastermind"
                 to explor expertise in the tech domain.
              </p>
              <h4 className="py-4 text-teal-600">
              <a href="https://devmastermind.blogspot.com/">Click Here</a>
              </h4>
              
            </div>
          </div>
        </section>
        
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">WORK EXPERIENCE</h3>
            
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
           
            <span className="text-teal-500"> Zligger Technologies Pvt Ltd | Dec 2020 - JUNE 2021 (6 months) </span>It is a learning integrated internship .
                In the first three months we were given
              an assignment every week.After the completion of each assignment it was
              evaluated and we recieved additional tasks to improve our knowledge and
              capabilities in those areas .After this process they got us directly involved in
              their company project
                    <br></br>
                    <br></br>
              <span className="text-teal-500"> Junior-Software Engineer -
               One Tech (Malaysia)| March- 2022 - Feb 2023 </span>
               Developed custom WordPress themes, plugins, and widgets
               Provided technical support for WordPress websites,
               Contributed to coding best practices and optimized website performance,
               Developed custom themes and plugins,
               Provided effective technical support to clients.

               <br></br>
                    <br></br>
              <span className="text-teal-500"> Freelace Software Engineer -
              Calipso (Startup) |Digital Marketing | March- 2021 - Feb 2023 </span>
              Responsible for developing and maintaining software solutions for CMS and
              POS systems ,
              Helped businesses manage their content and streamline their point of sale
              processes ,
              Contributed to coding best practices and optimized system performance
              <br></br>
              <br></br>
                            <span  className="text-teal-800">As a Social Media Specialist at Calipso</span> I created and implemented social
                            media campaigns, managed accounts, analyzed data, and provided clients
                            with regular reports and insights. I developed expertise in social media
                            strategy, content creation, analytics, and client communication, as well as
                            gained valuable experience in digital marketing, branding, and event
                            planning.
            </p>
            
          </div>
          <div>
            <h4 className="text-3xl py-10  dark:text-white">RESEARCHE & PROJECTS</h4>

            <h2 className="text-teal-500">Transport tracking system Model for public transport (RESEARCHE)</h2>
         
            <p className="text-md py-2 leading-8 text-gray-80  dark:text-white">
              The main objective of this bus tracking system is to get the real-time location of the bus
              and to have some general idea about the crowd so the passengers can better travel
                      decisions and also get a user friendly system to get the location and the density of the
                      passengers in the bus.The most important thing is that ,this processed system reduce the
                      wait time and the uncertainity time while increasing the user satisfication  . <span  className="text-teal-800">Flutter | Firebase</span></p>
                     <br></br>
                      {/* <h2 className="text-teal-500">Transport tracking system Model for public transport</h2>
         
            <p className="text-md py-2 leading-8 text-gray-80  dark:text-white">
              The main objective of this bus tracking system is to get the real-time location of the bus
              and to have some general idea about the crowd so the passengers can better travel
                      decisions and also get a user friendly system to get the location and the density of the
                      passengers in the bus.The most important thing is that ,this processed system reduce the
                      wait time and the uncertainity time while increasing the user satisfication  . <span  className="text-teal-800">Flutter | Firebase</span></p> */}
                      


       
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                onClick={() => handleImageClick(web1)}
              />   
                  
              This portfolio uses Next.js, React, JavaScript, HTML, CSS, Tailwind CSS, GitHub, Git,
               and the Image component provided by Next.js. These technologies are used to create a
                visually appealing and interactive portfolio website.   <br/>
                <br/>
                <a className= "bg-gradient-to-r bg-cyan-500  to-teal-500 text-white px-4 py-1  rounded-md ml-8" href="#">
                source code </a>
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"90%"}
                height={"80%"}
                layout="responsive"
                src={web2}
                onClick={() => handleImageClick(web2)}
              />
              <br></br>
              The PHP and MySQL Visitor Management System is a web application that efficiently manages
               and tracks visitors. It allows creating, reading, updating, and deleting visitor records using 
               PHP for server-side logic and MySQL for data storage.
               It simplifies visitor tracking, enhances security, and improves the visitor experience.            
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                onClick={() => handleImageClick(web3)}
              />        
              <br />    
              The provided code is for a meal search app that allows users to search for meals based on ingredients. It retrieves meal data from an API 
              and displays the results in the UI. Users can view recipe details for each meal, including instructions and a video link
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                onClick={() => handleImageClick(web4)}
              /> 
              <br />
              This Team Member assigning app enables users to manage employees by assigning them 
              to different teams. It offers filtering options based on teams and allows users to assign or 
              reassign employees to teams. The app provides a user-friendly interface to easily track and organize 
              employee assignments. Additionally, 
              it offers a grouped team members view to display the number of employees in each team.
              <br />           
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                onClick={() => handleImageClick(web5)}
              />    
              <br />
              This app is a shopping cart application that allows users to browse and purchase various products.
               It provides a user-friendly interface with features such as product filtering, sorting, 
               and a shopping cart to manage selected items. Users can search for products, view product details, 
               add items to the cart, and proceed to checkout. The app also includes a 
              rating system and options to filter products based on availability and fast delivery.        
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                onClick={() => handleImageClick(web6)}

              />     
              <br />
              The hospital management system is a PHP/MySQL-based application that streamlines hospital operations. 
              It enables efficient management of patient records, appointments, billing, and staff. With 
              a user-friendly interface and robust functionality, 
              it improves overall efficiency and organization in hospitals.
              <br></br>       
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web7}
                onClick={() => handleImageClick(web7)}
              />    
              <br/>
              The provided Flutter app calculates and displays the BMI (Body Mass Index) based on user input of height and 
              weight. It offers buttons to adjust the height and weight values and provides a visual representation of 
              gender selection. The app then determines the BMI category
               (Overweight, Normal, or Underweight) and presents the calculated BMI along with the corresponding result.        
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web8}
                onClick={() => handleImageClick(web8)}

              />      
              <br />
              The "ToDo" app is a simple task management application built using React.
               It allows users to add tasks to their to-do list, view the list of tasks for the day,
                and mark tasks as completed. The app utilizes React's useState hook to manage the state

                 of the new task input and the list of tasks. The ToDoList component is used to display the
                  list of tasks. Users can enter a task in the input field,
               click the "Add" button to add it to the list, and view their tasks for the day.    
               <br />  
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web10}
                onClick={() => handleImageClick(web10)}
              />     
              <br />
              This authentication app uses JSON Web Tokens (JWT) for secure user authentication in a Node.js environment. 
              It includes routes for user login, token generation, and protected routes. It ensures that only authenticated
               users with valid access tokens can access protected routes.
               This app provides a secure and efficient way to implement authentication in Node.js applications.
              <br />       
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web11}
                onClick={() => handleImageClick(web11)}

              />    
              <br/>
              The mug printing website enables users to customize and order personalized mugs with ease.
              . It offers a range of design options, including text and image customization, allowing users to
              create unique and personalized mugs. With a user-friendly interface, customers can easily navigate 
              through the available designs, preview their customized mug, and place their order hassle-free.
               It's a convenient and efficient platform for creating personalized mugs online        
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                onClick={() => handleImageClick(web1)}

              />            
            </div>
            </div>
            <div className="basis-1/4 flex-1 text-center shadow-lg shadow-zinc-900 p-10 rounded-xl my-10  dark:bg-white">
            <div className="basis-1/4 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                onClick={() => handleImageClick(web1)}

              />    
               <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
             
              <a className= "bg-gradient-to-r bg-cyan-500  to-teal-500 text-white px-4 py-1 align-l rounded-md ml-8" href="#">
                source code </a>        
            </div>
            </div>

            
          </div>
        </section>

        {showModal && (
        <div className="modal">
          <div className="modal-content">
            <span className="close" onClick={handleCloseModal}>
              &times;
            </span>
            <div className="image-modal">
              <Image
                className="rounded-lg object-cover"
                src={selectedImage}
                layout="responsive"
                width={950}
                height={600}
              />
              
            </div>
          </div>
        </div>
      )}
      </main>
    </div>
  );
}
